### ISSUE TITLE
No ligatures show in Visual Studio

### ISSUE THREAD

**Issue by Cirzen** [somq/consolas-ligaturized#1]
In the Windows fonts Settings page, I can see that the ligatures appear in the "preview" window, but when setting the Visual Studio 2019 default font, nothing shows up in the text editor.
Ligatures do work in with Fira Code.
Any idea what I might need to change to get them to show?

**Comment by somq** [comment]
Do you have your setting set like this? note the surrounding apostrophe (')
![settings](https://i.imgur.com/x7MKgJZ.png?1)
At least I can say that for me and many others it works on win7/10.

**Comment by Cirzen** [comment]
Hey, thanks for the reply! Is that the settings for VSCode? I'm talking about Visual Studio Professional 2019. The editor font is selected in a drop down box. I'll post a pic once I get back to my desk tomorrow.

**Comment by Cirzen** [comment]
![image](https://user-images.githubusercontent.com/13346199/64103456-36bb9000-cd6a-11e9-95af-a05895737249.png)
As promised. Note that the `=>` is not ligaturized in the code sample just above.
But if I switch to Fira Code:
![image](https://user-images.githubusercontent.com/13346199/64103886-0fb18e00-cd6b-11e9-9476-c0df7ec2ba40.png)

**Comment by Cirzen** [comment]
Pleased to report that a machine reboot has fixed this! Thanks again. I'll close the issue.
