### ISSUE TITLE
The hash-curly brace ligature is vertically offset from the right curly-brace

### ISSUE THREAD

**Issue by Misophistful** [somq/consolas-ligaturized#11]
<img width="534" alt="Screen Shot 2020-11-29 at 09 31 48" src="https://user-images.githubusercontent.com/5363984/100537124-13f68080-3226-11eb-9bfd-9011c5609a0b.png">

**Comment by somq** [comment]
Unfortunately, there is not much we can do about this issue since we depends on FiraCode.   
The issue probably belongs to them.
