### ISSUE TITLE
Numbers aren't vertically centered within brackets

### ISSUE THREAD

**Issue by Misophistful** [somq/consolas-ligaturized#12]
<img width="483" alt="Screen Shot 2020-11-29 at 09 36 25" src="https://user-images.githubusercontent.com/5363984/100537188-98490380-3226-11eb-87b3-de5880382ba8.png">

**Comment by somq** [comment]
Unfortunately, there is not much we can do about this issue since we depends on FiraCode.   
The issue probably belongs to them.
