### ISSUE TITLE
Consolas Ligaturized font messes up my italic fonts

### ISSUE THREAD

**Issue by takos22** [somq/consolas-ligaturized#14]
I have italics set up for the keywords, but this font adds other italics which aren't that good, is there a way to remove the italic characters of this font to use the old ones. 

How it looks with my italics and no ligatures:
![image](https://user-images.githubusercontent.com/59511469/116976036-df00c500-acc0-11eb-8a30-a6cdb6a5d1af.png)
How it looks with the new italics and ligatures:
![image](https://user-images.githubusercontent.com/59511469/116976091-f50e8580-acc0-11eb-9464-47d0026b3ca9.png)

As you can see, the new italics look pretty weird, so I would want to remove them in order to use my old ones.

**Comment by somq** [comment]
Unfortunately, there is not much we can do about this issue since we depends on FiraCode.   
The issue probably belongs to them.
