### ISSUE TITLE
Single Arrow does not work in Visual Studio

### ISSUE THREAD

**Issue by mt-xing** [somq/consolas-ligaturized#6]
The single arrow `->` does not show up as a ligature in Visual Studio 2019. All other ligatures work fine. The single arrow works fine in other IDEs.

In VS Code:
![image](https://user-images.githubusercontent.com/6147405/77562961-0dde2200-6e97-11ea-922e-0cee78ddac48.png)

In VS Enterprise 2019:
![image](https://user-images.githubusercontent.com/6147405/77563059-277f6980-6e97-11ea-925a-b5c41d7cfd61.png)
Note other ligatures work fine; only the `->` is broken.

**Comment by somq** [comment]
Can you try with v2 please ?

**Comment by mt-xing** [comment]
> Can you try with v2 please ?

![image](https://user-images.githubusercontent.com/6147405/81834418-e60e5080-950e-11ea-9807-190bfa8bc173.png)

Just updated; still broken. :( 

![image](https://user-images.githubusercontent.com/6147405/81834449-f0304f00-950e-11ea-973f-8cedd11ea255.png)

**Comment by somq** [comment]
Seems like it's a vs 2019 issue as tracked [here (github)](https://github.com/microsoft/cascadia-code/issues/107) and [here (microsoft)](https://developercommunity.visualstudio.com/idea/591741/font-ligatures-not-working.html).
