### ISSUE TITLE
Update ligatures to FiraCode v3

### ISSUE THREAD

**Issue by somq** [somq/consolas-ligaturized#8]
Update FiraCode ligatures to [v3](https://github.com/tonsky/FiraCode/releases/tag/3.1) when [this](https://github.com/ToxicFrog/Ligaturizer/issues/85) issue is closed.

**Comment by somq** [comment]
Blocked by: https://github.com/ToxicFrog/Ligaturizer/issues/89

**Comment by ToxicFrog** [comment]
Ligaturizer has now been updated to Fira Code 3.1. Support for 4+ will require significant changes due the way ligature support in Fira has changed, but if you were just waiting on 3.x support you should be good to go now.

**Comment by nhatthm** [comment]
@somq you can close this issue
